# Generated by Django 4.0.1 on 2022-03-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_userworkout_categories_delete_workout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseCategory',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='categories',
            field=models.ManyToManyField(to='routine.WorkoutCategory'),
        ),
    ]
