# Generated by Django 4.0.1 on 2022-03-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0006_userroutine_categories_userroutine_private_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroutine',
            old_name='private',
            new_name='is_private',
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_exercises', to='routine.exercise'),
        ),
        migrations.AlterField(
            model_name='userworkout',
            name='routine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_workouts', to='routine.userroutine'),
        ),
    ]
