# Generated by Django 4.0.3 on 2022-03-13 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0008_alter_userexercise_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userworkout',
            name='categories',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='categories',
            field=models.ManyToManyField(related_name='exercises', to='routine.workoutcategory'),
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='routine.exercise'),
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_exercises', to='routine.userworkout'),
        ),
    ]
