# Generated by Django 4.0.3 on 2022-03-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0009_remove_userworkout_categories_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutCategory',
            new_name='ExerciseCategory',
        ),
    ]
